### ISSUE TITLE
Columns data disappear.

### ISSUE THREAD

**Issue by Abd-el-hamid** [maliMirkec/angular-dragtable#1]
Hi,
Thanks for this good directive. It works well on some tables but in others after draging a column it data disappear like in the pictrue below.
![1](https://user-images.githubusercontent.com/27816598/28882097-becaa61c-7799-11e7-8475-67d1fb181306.png)
![2](https://user-images.githubusercontent.com/27816598/28882102-c0b32b48-7799-11e7-9a03-414e5436c34c.png)

**EDIT:**
I figured out that this happens when using two tables in the same page. Is there a way to fix this ?

**Comment by maliMirkec** [comment]
I'm not sure, I'll have to check.
Do you have unique IDs on both tables?

**Comment by mauryashashi** [comment]
I also faced the same issue with multiple table in a page and notable this do not happen with first table. Following is workaround for this.

In ghostTable function, while appending ghost data elements start counter from 1 instead of 0.
 `for (var i = 1; i < tdLimit; i++) `

**Comment by maliMirkec** [comment]
@mauryashashi, could you make this change in a pull request?
