### ISSUE TITLE
Can I get new order  list after drop?

### ISSUE THREAD

**Issue by ganeshjadhav20** [maliMirkec/angular-dragtable#3]

**Comment by maliMirkec** [comment]
Did you manage to find a solution? Could you listen to `dragend` event and then reorder using filter or something?

**Comment by ganeshjadhav20** [comment]
No,I am not able to listen dragend event.I want to save reorder after change its sequence . If you please provide some idea about how to listen this event.
Thanks in advance

**Comment by maliMirkec** [comment]
Try this.

```js
document.querySelectorAll('[drag-me]').forEach(function(elem) {
  elem.addEventListener('dragend', function(e) {
    console.log('test', 1);
  });
})
```

Let me know if it works.

**Comment by maliMirkec** [comment]
@ganeshjadhav20 Any luck? Can I close the issue?

**Comment by maliMirkec** [comment]
Closing.
