### ISSUE TITLE
Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by eddie797** [maliMirkec/angular-dragtable#4]
Hello,

I can't seem to run the dragtable.js when I do, it says the angular is not defined.

"angular.module('Dragtable', [])" In the .js file it gives a red cross next to this.

**Comment by maliMirkec** [comment]
Did you include Angular before the dragtable.js script?

**Comment by eddie797** [comment]
Do you mean this?

https://www.npmjs.com/package/angular

**Comment by maliMirkec** [comment]
Exactly. Make sure to include angular framework before angular-dragtable.
